'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  clsCliente.vb
''  Implementation of the Class clsCliente
''  Generated by Enterprise Architect
''  Created on:      21-oct-2010 05:15:37 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports bddc.BEC.COM

Namespace CLI
    Public Class clsClienteConsumo
        Inherits COM.clsAuditoria


        Private decClienteConsumoRank As Decimal
        Private strClienteConsumoIdkey As String
        Private strClienteConsumoDl As String
        Private strClienteConsumoCmsid As String
        Private strClienteConsumoSname As String
        Private strClienteConsumoLname As String
        Private strClienteConsumoFname As String
        Private strClienteConsumoAddress As String
        Private strClienteConsumoCity As String
        Private strClienteConsumoState As String
        Private strClienteConsumoZip As String
        Private strClienteConsumoEmail As String
        Private strClienteConsumoMailOk As String
        Private strClienteConsumoBmnth As String
        Private strClienteConsumoBday As String
        Private strClienteConsumoByear As String
        Private strClienteConsumoGender As String
        Private strClienteConsumoSoc As String
        Private strClienteConsumoPhone As String
        Private strClienteConsumoCellnum As String
        Private decClienteConsumoPointBal As Decimal
        Private decClienteConsumoCompBal As Decimal
        Private decClienteConsumoPointsEarned As Decimal
        Private decClienteConsumoVisits As Decimal
        Private decClienteConsumoTotalTheo As Decimal
        Private decClienteConsumoSlotTheo As Decimal
        Private decClienteConsumoTableTheo As Decimal
        Private decClienteConsumoSlotPoints As Decimal
        Private decClienteConsumoSlotWager As Decimal
        Private decClienteConsumoSlotWon As Decimal
        Private decClienteConsumoTablePoints As Decimal
        Private decClienteConsumoTableMins As Decimal
        Private decClienteConsumoTableAve As Decimal
        Private decClienteConsumoTableBuy As Decimal
        Private decClienteConsumoTableWalk As Decimal
        Private intClienteConsumoTableTier As Integer


        Public Sub New()

            decClienteConsumoRank = 0
            strClienteConsumoIdkey = ""
            strClienteConsumoDl = ""
            strClienteConsumoCmsid = ""
            strClienteConsumoSname = ""
            strClienteConsumoLname = ""
            strClienteConsumoFname = ""
            strClienteConsumoAddress = ""
            strClienteConsumoCity = ""
            strClienteConsumoState = ""
            strClienteConsumoZip = ""
            strClienteConsumoEmail = ""
            strClienteConsumoMailOk = ""
            strClienteConsumoBmnth = ""
            strClienteConsumoBday = ""
            strClienteConsumoByear = ""
            strClienteConsumoGender = ""
            strClienteConsumoSoc = ""
            strClienteConsumoPhone = ""
            strClienteConsumoCellnum = ""
            decClienteConsumoPointBal = 0
            decClienteConsumoCompBal = 0
            decClienteConsumoPointsEarned = 0
            decClienteConsumoVisits = 0
            decClienteConsumoTotalTheo = 0
            decClienteConsumoSlotTheo = 0
            decClienteConsumoTableTheo = 0
            decClienteConsumoSlotPoints = 0
            decClienteConsumoSlotWager = 0
            decClienteConsumoSlotWon = 0
            decClienteConsumoTablePoints = 0
            decClienteConsumoTableMins = 0
            decClienteConsumoTableAve = 0
            decClienteConsumoTableBuy = 0
            decClienteConsumoTableWalk = 0
            intClienteConsumoTableTier = 0
        End Sub

        Public Property ClienteConsumoRank() As Decimal
            Get
                Return decClienteConsumoRank
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoRank = Value
            End Set
        End Property

        Public Property ClienteConsumoIdkey() As String
            Get
                Return strClienteConsumoIdkey
            End Get
            Set(ByVal Value As String)
                strClienteConsumoIdkey = Value
            End Set
        End Property

        Public Property ClienteConsumoDl() As String
            Get
                Return strClienteConsumoDl
            End Get
            Set(ByVal Value As String)
                strClienteConsumoDl = Value
            End Set
        End Property

        Public Property ClienteConsumoCmsid() As String
            Get
                Return strClienteConsumoCmsid
            End Get
            Set(ByVal Value As String)
                strClienteConsumoCmsid = Value
            End Set
        End Property

        Public Property ClienteConsumoSname() As String
            Get
                Return strClienteConsumoSname
            End Get
            Set(ByVal Value As String)
                strClienteConsumoSname = Value
            End Set
        End Property

        Public Property ClienteConsumoLname() As String
            Get
                Return strClienteConsumoLname
            End Get
            Set(ByVal Value As String)
                strClienteConsumoLname = Value
            End Set
        End Property

        Public Property ClienteConsumoFname() As String
            Get
                Return strClienteConsumoFname
            End Get
            Set(ByVal Value As String)
                strClienteConsumoFname = Value
            End Set
        End Property

        Public Property ClienteConsumoAddress() As String
            Get
                Return strClienteConsumoAddress
            End Get
            Set(ByVal Value As String)
                strClienteConsumoAddress = Value
            End Set
        End Property

        Public Property ClienteConsumoCity() As String
            Get
                Return strClienteConsumoCity
            End Get
            Set(ByVal Value As String)
                strClienteConsumoCity = Value
            End Set
        End Property

        Public Property ClienteConsumoState() As String
            Get
                Return strClienteConsumoState
            End Get
            Set(ByVal Value As String)
                strClienteConsumoState = Value
            End Set
        End Property

        Public Property ClienteConsumoZip() As String
            Get
                Return strClienteConsumoZip
            End Get
            Set(ByVal Value As String)
                strClienteConsumoZip = Value
            End Set
        End Property

        Public Property ClienteConsumoEmail() As String
            Get
                Return strClienteConsumoEmail
            End Get
            Set(ByVal Value As String)
                strClienteConsumoEmail = Value
            End Set
        End Property

        Public Property ClienteConsumoMailOk() As String
            Get
                Return strClienteConsumoMailOk
            End Get
            Set(ByVal Value As String)
                strClienteConsumoMailOk = Value
            End Set
        End Property

        Public Property ClienteConsumoBmnth() As String
            Get
                Return strClienteConsumoBmnth
            End Get
            Set(ByVal Value As String)
                strClienteConsumoBmnth = Value
            End Set
        End Property

        Public Property ClienteConsumoBday() As String
            Get
                Return strClienteConsumoBday
            End Get
            Set(ByVal Value As String)
                strClienteConsumoBday = Value
            End Set
        End Property

        Public Property ClienteConsumoByear() As String
            Get
                Return strClienteConsumoByear
            End Get
            Set(ByVal Value As String)
                strClienteConsumoByear = Value
            End Set
        End Property

        Public Property ClienteConsumoGender() As String
            Get
                Return strClienteConsumoGender
            End Get
            Set(ByVal Value As String)
                strClienteConsumoGender = Value
            End Set
        End Property

        Public Property ClienteConsumoSoc() As String
            Get
                Return strClienteConsumoSoc
            End Get
            Set(ByVal Value As String)
                strClienteConsumoSoc = Value
            End Set
        End Property

        Public Property ClienteConsumoPhone() As String
            Get
                Return strClienteConsumoPhone
            End Get
            Set(ByVal Value As String)
                strClienteConsumoPhone = Value
            End Set
        End Property

        Public Property ClienteConsumoCellnum() As String
            Get
                Return strClienteConsumoCellnum
            End Get
            Set(ByVal Value As String)
                strClienteConsumoCellnum = Value
            End Set
        End Property

        Public Property ClienteConsumoPointBal() As Decimal
            Get
                Return decClienteConsumoPointBal
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoPointBal = Value
            End Set
        End Property

        Public Property ClienteConsumoCompBal() As Decimal
            Get
                Return decClienteConsumoCompBal
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoCompBal = Value
            End Set
        End Property

        Public Property ClienteConsumoPointsEarned() As Decimal
            Get
                Return decClienteConsumoPointsEarned
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoPointsEarned = Value
            End Set
        End Property

        Public Property ClienteConsumoVisits() As Decimal
            Get
                Return decClienteConsumoVisits
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoVisits = Value
            End Set
        End Property

        Public Property ClienteConsumoTotalTheo() As Decimal
            Get
                Return decClienteConsumoTotalTheo
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTotalTheo = Value
            End Set
        End Property

        Public Property ClienteConsumoSlotTheo() As Decimal
            Get
                Return decClienteConsumoSlotTheo
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoSlotTheo = Value
            End Set
        End Property

        Public Property ClienteConsumoTableTheo() As Decimal
            Get
                Return decClienteConsumoTableTheo
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTableTheo = Value
            End Set
        End Property

        Public Property ClienteConsumoSlotPoints() As Decimal
            Get
                Return decClienteConsumoSlotPoints
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoSlotPoints = Value
            End Set
        End Property

        Public Property ClienteConsumoSlotWager() As Decimal
            Get
                Return decClienteConsumoSlotWager
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoSlotWager = Value
            End Set
        End Property

        Public Property ClienteConsumoSlotWon() As Decimal
            Get
                Return decClienteConsumoSlotWon
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoSlotWon = Value
            End Set
        End Property

        Public Property ClienteConsumoTablePoints() As Decimal
            Get
                Return decClienteConsumoTablePoints
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTablePoints = Value
            End Set
        End Property

        Public Property ClienteConsumoTableMins() As Decimal
            Get
                Return decClienteConsumoTableMins
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTableMins = Value
            End Set
        End Property

        Public Property ClienteConsumoTableAve() As Decimal
            Get
                Return decClienteConsumoTableAve
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTableAve = Value
            End Set
        End Property

        Public Property ClienteConsumoTableBuy() As Decimal
            Get
                Return decClienteConsumoTableBuy
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTableBuy = Value
            End Set
        End Property

        Public Property ClienteConsumoTableWalk() As Decimal
            Get
                Return decClienteConsumoTableWalk
            End Get
            Set(ByVal Value As Decimal)
                decClienteConsumoTableWalk = Value
            End Set
        End Property

        Public Property ClienteConsumoTableTier() As Integer
            Get
                Return intClienteConsumoTableTier
            End Get
            Set(ByVal Value As Integer)
                intClienteConsumoTableTier = Value
            End Set
        End Property

    End Class ' clsClienteConsumo

End Namespace ' CLI