'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  clsMovimiento.vb
''  Implementation of the Class clsMovimiento
''  Generated by Enterprise Architect
''  Created on:      30-Mar-2010 10:05:41 a.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace CLI

    Public Class clsMovimiento
        Inherits COM.clsAuditoria

        Private intMovimientoId As Integer
        Private intClienteId As Integer
        Private intTipoJuegoId As Integer
        Private strMovimientoFecha As String
        Private strMovimientoNroMesa As String
        Private intMovimientoMonedaId As Integer
        Private decMovimientoDrop As Decimal
        Private decMovimientoWinLoss As Decimal
        Private decMovimientoApuestaProm As Decimal
        Private strMovimientoHoraIni As String
        Private strMovimientoHoraFin As String
        Private decMovimientoDuracionHr As Decimal
        Private decFactorPasesHora As Decimal
        Private intMovimientoEstadoId As Integer

        Public Property MovimientoId() As Integer
            Get
                Return intMovimientoId
            End Get
            Set(ByVal Value As Integer)
                intMovimientoId = Value
            End Set
        End Property

        Public Property ClienteId() As Integer
            Get
                Return intClienteId
            End Get
            Set(ByVal Value As Integer)
                intClienteId = Value
            End Set
        End Property

        Public Property TipoJuegoId() As Integer
            Get
                Return intTipoJuegoId
            End Get
            Set(ByVal Value As Integer)
                intTipoJuegoId = Value
            End Set
        End Property

        Public Property MovimientoFecha() As String
            Get
                Return strMovimientoFecha
            End Get
            Set(ByVal Value As String)
                strMovimientoFecha = Value
            End Set
        End Property

        Public Property MovimientoNroMesa() As String
            Get
                Return strMovimientoNroMesa
            End Get
            Set(ByVal Value As String)
                strMovimientoNroMesa = Value
            End Set
        End Property

        Public Property MovimientoMonedaId() As Integer
            Get
                Return intMovimientoMonedaId
            End Get
            Set(ByVal Value As Integer)
                intMovimientoMonedaId = Value
            End Set
        End Property

        Public Property MovimientoDrop() As Decimal
            Get
                Return decMovimientoDrop
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoDrop = Value
            End Set
        End Property

        Public Property MovimientoWinLoss() As Decimal
            Get
                Return decMovimientoWinLoss
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoWinLoss = Value
            End Set
        End Property

        Public Property MovimientoApuestaProm() As Decimal
            Get
                Return decMovimientoApuestaProm
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoApuestaProm = Value
            End Set
        End Property

        Public Property MovimientoHoraIni() As String
            Get
                Return strMovimientoHoraIni
            End Get
            Set(ByVal Value As String)
                strMovimientoHoraIni = Value
            End Set
        End Property

        Public Property MovimientoHoraFin() As String
            Get
                Return strMovimientoHoraFin
            End Get
            Set(ByVal Value As String)
                strMovimientoHoraFin = Value
            End Set
        End Property

        Public Property MovimientoDuracionHr() As Decimal
            Get
                Return decMovimientoDuracionHr
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoDuracionHr = Value
            End Set
        End Property

        Public Property FactorPasesHora() As Decimal
            Get
                Return decFactorPasesHora
            End Get
            Set(ByVal Value As Decimal)
                decFactorPasesHora = Value
            End Set
        End Property

        Public Property MovimientoEstadoId() As Integer
            Get
                Return intMovimientoEstadoId
            End Get
            Set(ByVal Value As Integer)
                intMovimientoEstadoId = Value
            End Set
        End Property


    End Class ' clsMovimiento

End Namespace ' CLI