'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  rptCliente.vb
''  Implementation of the Class rptCliente
''  Generated by Enterprise Architect
''  Created on:      03-nov-2010 06:04:25 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace CLI
	Public Class rptCliente


		Private intClienteId As Integer
		Private strClienteCodigo As String
		Private strClienteApellidos As String
		Private strClienteNombres As String
		Private strClienteFecNac As String
		Private intClienteGeneroId As Integer
		Private strClienteGenero As String
		Private strDomicilioCiudad As String
		Private strClienteTelefonos As String
        Private strClienteCorreoElectronico As String
        Private strClienteEdad As String

		Public Property ClienteId() As Integer
			Get
				Return intClienteId
			End Get
			Set(ByVal Value as Integer)
				intClienteId = Value
			End Set
		End Property

        Public Property ClienteCodigo() As String
            Get
                Return strClienteCodigo
            End Get
            Set(ByVal Value As String)
                strClienteCodigo = Value
            End Set
        End Property

		Public Property ClienteApellidos() As String
			Get
				Return strClienteApellidos
			End Get
			Set(ByVal Value as String)
				strClienteApellidos = Value
			End Set
		End Property

		Public Property ClienteNombres() As String
			Get
				Return strClienteNombres
			End Get
			Set(ByVal Value as String)
				strClienteNombres = Value
			End Set
		End Property

		Public Property ClienteFecNac() As String
			Get
				Return strClienteFecNac
			End Get
			Set(ByVal Value as String)
				strClienteFecNac = Value
			End Set
        End Property

        Public Property ClienteEdad() As String
            Get
                Return strClienteEdad
            End Get
            Set(ByVal Value As String)
                strClienteEdad = Value
            End Set
        End Property

		Public Property ClienteGeneroId() As Integer
			Get
				Return intClienteGeneroId
			End Get
			Set(ByVal Value as Integer)
				intClienteGeneroId = Value
			End Set
		End Property

		Public Property ClienteGenero() As String
			Get
				Return strClienteGenero
			End Get
			Set(ByVal Value as String)
				strClienteGenero = Value
			End Set
		End Property

		Public Property DomicilioCiudad() As String
			Get
				Return strDomicilioCiudad
			End Get
			Set(ByVal Value as String)
				strDomicilioCiudad = Value
			End Set
		End Property

		Public Property ClienteTelefonos() As String
			Get
				Return strClienteTelefonos
			End Get
			Set(ByVal Value as String)
				strClienteTelefonos = Value
			End Set
		End Property

		Public Property ClienteCorreoElectronico() As String
			Get
				Return strClienteCorreoElectronico
			End Get
			Set(ByVal Value as String)
				strClienteCorreoElectronico = Value
			End Set
		End Property


	End Class ' rptCliente

End Namespace ' CLI