'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  rptClienteMesas.vb
''  Implementation of the Class rptClienteMesas
''  Generated by Enterprise Architect
''  Created on:      03-nov-2010 05:16:56 p.m.
''  Original author: Alejandro Borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports bddc.BEC.CLI

Namespace CLI
	Public Class rptClienteMesas
		Inherits CLI.rptCliente


		Private decDropTotal As Decimal
		Private decWinLossTotal As Decimal
		Private decApuestaPromtotal As Decimal
		Private decTiempoTotal As Decimal

		Public Property DropTotal() As Decimal
			Get
				Return decDropTotal
			End Get
			Set(ByVal Value as Decimal)
				decDropTotal = Value
			End Set
		End Property

		Public Property WinLossTotal() As Decimal
			Get
				Return decWinLossTotal
			End Get
			Set(ByVal Value as Decimal)
				decWinLossTotal = Value
			End Set
		End Property

		Public Property ApuestaPromtotal() As Decimal
			Get
				Return decApuestaPromtotal
			End Get
			Set(ByVal Value as Decimal)
				decApuestaPromtotal = Value
			End Set
		End Property

		Public Property TiempoTotal() As Decimal
			Get
				Return decTiempoTotal
			End Get
			Set(ByVal Value as Decimal)
				decTiempoTotal = Value
			End Set
		End Property


	End Class ' rptClienteMesas

End Namespace ' CLI