'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  viwClienteTicket.vb
''  Implementation of the Class viwClienteTicket
''  Generated by Enterprise Architect
''  Created on:      24-sep-2010 06:51:44 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace CLI
	Public Class viwClienteTicket


		Private datTicketsFechaImpresion As DateTime
		Private decTicketsTotal As Decimal
		Private intAudUsuarioId As Integer
		Private intClienteCategoriaId As Integer
		Private intClienteId As Integer
		Private intTicketsImpresionEstadoId As Integer
		Private intTicketsImpresos As Integer
		Private intTicketsNumImpresiones As Integer
		Private intTicketsPendientes As Integer
		Private intTipoJuegoId As Integer
		Private strClienteCodigo As String
		Private strClienteNombreCompleto As String
		Private strClienteNumDoc As String
		Private strClienteNumTarjeta As String
		''' <summary>
		''' ID generado por la aplicacion
		''' </summary>
		Private strTicketsGUID As String
		Private strTicketsNumInicial As String

		Public Property AudUsuarioId() As Integer
			Get
				Return intAudUsuarioId
			End Get
			Set(ByVal Value as Integer)
				intAudUsuarioId = Value
			End Set
		End Property

		Public Property ClienteCategoriaId() As Integer
			Get
				Return intClienteCategoriaId
			End Get
			Set(ByVal Value as Integer)
				intClienteCategoriaId = Value
			End Set
		End Property

		Public Property ClienteCodigo() As String
			Get
				Return strClienteCodigo
			End Get
			Set(ByVal Value as String)
				strClienteCodigo = Value
			End Set
		End Property

		Public Property ClienteId() As Integer
			Get
				Return intClienteId
			End Get
			Set(ByVal Value as Integer)
				intClienteId = Value
			End Set
		End Property

		Public Property ClienteNombreCompleto() As String
			Get
				Return strClienteNombreCompleto
			End Get
			Set(ByVal Value as String)
				strClienteNombreCompleto = Value
			End Set
		End Property

		Public Property ClienteNumDoc() As String
			Get
				Return strClienteNumDoc
			End Get
			Set(ByVal Value as String)
				strClienteNumDoc = Value
			End Set
		End Property

		Public Property ClienteNumTarjeta() As String
			Get
				Return strClienteNumTarjeta
			End Get
			Set(ByVal Value as String)
				strClienteNumTarjeta = Value
			End Set
		End Property

		Public Property TicketsFechaImpresion() As DateTime
			Get
				Return datTicketsFechaImpresion
			End Get
			Set(ByVal Value as DateTime)
				datTicketsFechaImpresion = Value
			End Set
		End Property

		''' <summary>
		''' ID generado por la aplicacion
		''' </summary>
		Public Property TicketsGUID() As String
			Get
				Return strTicketsGUID
			End Get
			Set(ByVal Value as String)
				strTicketsGUID = Value
			End Set
		End Property

		Public Property TicketsImpresionEstadoId() As Integer
			Get
				Return intTicketsImpresionEstadoId
			End Get
			Set(ByVal Value as Integer)
				intTicketsImpresionEstadoId = Value
			End Set
		End Property

		Public Property TicketsImpresos() As Integer
			Get
				Return intTicketsImpresos
			End Get
			Set(ByVal Value as Integer)
				intTicketsImpresos = Value
			End Set
		End Property

		Public Property TicketsNumImpresiones() As Integer
			Get
				Return intTicketsNumImpresiones
			End Get
			Set(ByVal Value as Integer)
				intTicketsNumImpresiones = Value
			End Set
		End Property

		Public Property TicketsNumInicial() As String
			Get
				Return strTicketsNumInicial
			End Get
			Set(ByVal Value as String)
				strTicketsNumInicial = Value
			End Set
		End Property

		Public Property TicketsPendientes() As Integer
			Get
				Return intTicketsPendientes
			End Get
			Set(ByVal Value as Integer)
				intTicketsPendientes = Value
			End Set
		End Property

		Public Property TicketsTotal() As Decimal
			Get
				Return decTicketsTotal
			End Get
			Set(ByVal Value as Decimal)
				decTicketsTotal = Value
			End Set
		End Property

		Public Property TipoJuegoId() As Integer
			Get
				Return intTipoJuegoId
			End Get
			Set(ByVal Value as Integer)
				intTipoJuegoId = Value
			End Set
		End Property


	End Class ' viwClienteTicket

End Namespace ' CLI