'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  viwCliente.vb
''  Implementation of the Class viwCliente
''  Generated by Enterprise Architect
''  Created on:      27-May-2010 05:48:34 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Option Explicit On
Option Strict On

Namespace CLI
	Public Class viwCliente

		Private intClienteId As Integer
		Private strClienteCodigo As String
		Private strClienteApePat As String
		Private strClienteApeMat As String
		Private strClienteNombres As String
		Private strClienteNombreCompleto As String
        Private intClienteEstadoId As Integer
        'Private strClienteNacionalidad As String

		Public Property ClienteId() As Integer
			Get
				Return intClienteId
			End Get
			Set(ByVal Value as Integer)
				intClienteId = Value
			End Set
        End Property

        'Public Property ClienteNacionalidad() As String
        '    Get
        '        Return strClienteNacionalidad
        '    End Get
        '    Set(ByVal Value As String)
        '        strClienteNacionalidad = Value
        '    End Set
        'End Property

		Public Property ClienteCodigo() As String
			Get
				Return strClienteCodigo
			End Get
			Set(ByVal Value as String)
				strClienteCodigo = Value
			End Set
		End Property

		Public ReadOnly Property ClienteApellidos() As String
			Get
			   Return strClienteApePat & " " & strClienteApeMat
			End Get
	
		End Property

		Public Property ClienteApePat() As String
			Get
				Return strClienteApePat
			End Get
			Set(ByVal Value as String)
				strClienteApePat = Value
			End Set
		End Property

		Public Property ClienteApeMat() As String
			Get
				Return strClienteApeMat
			End Get
			Set(ByVal Value as String)
				strClienteApeMat = Value
			End Set
		End Property

		Public Property ClienteNombres() As String
			Get
				Return strClienteNombres
			End Get
			Set(ByVal Value as String)
				strClienteNombres = Value
			End Set
		End Property

		Public Property ClienteNombreCompleto() As String
			Get
				Return strClienteNombreCompleto
			End Get
			Set(ByVal Value as String)
				strClienteNombreCompleto = Value
			End Set
		End Property

		Public Sub New()

		End Sub

		Public Property ClienteEstadoId() As Integer
			Get
				Return intClienteEstadoId
			End Get
			Set(ByVal Value as Integer)
				intClienteEstadoId = Value
			End Set
		End Property

	End Class ' viwCliente

End Namespace ' CLI