'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  viwMovimiento.vb
''  Implementation of the Class viwMovimiento
''  Generated by Enterprise Architect
''  Created on:      30-Mar-2010 10:21:01 a.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace CLI

    Public Class viwMovimiento


        Private intMovimientoId As Integer
        Private strTipoJuego As String
        Private strMovimientoFecha As String
        Private strMovimientoNroMesa As String
        Private strMovimientoMoneda As String
        Private decMovimientoDrop As Decimal
        Private decMovimientoWinLoss As Decimal
        Private decMovimientoApuestaProm As Decimal
        Private strMovimientoHoraIni As String
        Private strMovimientoHoraFin As String
        Private decMovimientoDuracionHr As Decimal

        Public Property MovimientoId() As Integer
            Get
                Return intMovimientoId
            End Get
            Set(ByVal Value As Integer)
                intMovimientoId = Value
            End Set
        End Property

        Public Property TipoJuego() As String
            Get
                Return strTipoJuego
            End Get
            Set(ByVal Value As String)
                strTipoJuego = Value
            End Set
        End Property

        Public Property MovimientoFecha() As String
            Get
                Return strMovimientoFecha
            End Get
            Set(ByVal Value As String)
                strMovimientoFecha = Value
            End Set
        End Property

        Public Property MovimientoNroMesa() As String
            Get
                Return strMovimientoNroMesa
            End Get
            Set(ByVal Value As String)
                strMovimientoNroMesa = Value
            End Set
        End Property

        Public Property MovimientoMoneda() As String
            Get
                Return strMovimientoMoneda
            End Get
            Set(ByVal Value As String)
                strMovimientoMoneda = Value
            End Set
        End Property

        Public Property MovimientoDrop() As Decimal
            Get
                Return decMovimientoDrop
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoDrop = Value
            End Set
        End Property

        Public Property MovimientoWinLoss() As Decimal
            Get
                Return decMovimientoWinLoss
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoWinLoss = Value
            End Set
        End Property

        Public Property MovimientoApuestaProm() As Decimal
            Get
                Return decMovimientoApuestaProm
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoApuestaProm = Value
            End Set
        End Property

        Public Property MovimientoHoraIni() As String
            Get
                Return strMovimientoHoraIni
            End Get
            Set(ByVal Value As String)
                strMovimientoHoraIni = Value
            End Set
        End Property

        Public Property MovimientoHoraFin() As String
            Get
                Return strMovimientoHoraFin
            End Get
            Set(ByVal Value As String)
                strMovimientoHoraFin = Value
            End Set
        End Property

        Public Property MovimientoDuracionHr() As Decimal
            Get
                Return decMovimientoDuracionHr
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoDuracionHr = Value
            End Set
        End Property


    End Class ' viwMovimiento

End Namespace ' CLI