'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  clsEstimadoMesa.vb
''  Implementation of the Class clsEstimadoMesa
''  Generated by Enterprise Architect
''  Created on:      24-Jun-2010 12:14:42 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace FJM
    Public Class clsEstimadoMesa
        Inherits COM.clsAuditoria

        Private intEstimadoMesaId As Integer
        Private strEstimadoMesaFecha As String
        Private intMesaId As Integer
        Private strEstimadoMesaLista As String

        Public Property EstimadoMesaId() As Integer
            Get
                Return intEstimadoMesaId
            End Get
            Set(ByVal Value As Integer)
                intEstimadoMesaId = Value
            End Set
        End Property

        Public Property EstimadoMesaFecha() As String
            Get
                Return strEstimadoMesaFecha
            End Get
            Set(ByVal Value As String)
                strEstimadoMesaFecha = Value
            End Set
        End Property

        Public Property MesaId() As Integer
            Get
                Return intMesaId
            End Get
            Set(ByVal Value As Integer)
                intMesaId = Value
            End Set
        End Property

        Public Property EstimadoMesaLista() As String
            Get
                Return strEstimadoMesaLista
            End Get
            Set(ByVal Value As String)
                strEstimadoMesaLista = Value
            End Set
        End Property


        Public Sub New()
            intEstimadoMesaId = 0
            intMesaId = 0
        End Sub

    End Class ' clsEstimadoMesa

End Namespace ' CLI