'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  clsOperacionMesa.vb
''  Implementation of the Class clsOperacionMesa
''  Generated by Enterprise Architect
''  Created on:      18-oct-2010 05:39:15 p.m.
''  Original author: Alejandro Borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict Off

Namespace FJM
    Public Class clsOperacionMesa
        Inherits COM.clsAuditoria


        Private intOperacionMesaId As Integer
        Private strFechaProceso As String
        Private intTipoOperacionId As Integer
        Private strTipoOperacion As String
        Private intTipoJuegoId As Integer
        Private strTipoJuego As String
        Private strNroMesa As String
        ''' <summary>
        ''' Dealer|Pitboss|Supervisor|Inspector
        ''' </summary>
        Private strPersonalAsignado As String
        Private strComentarios As String
        Private strDenominaciones As String
        ''' <summary>
        ''' Concatenar por denominaciones. Ejm. #monedas de 5000|# monedas de 1000|...
        ''' </summary>
        Private strFlotaFichas As String
        Private decMontoTotal As Decimal
        Private intEstadoId As Integer

        Public Property OperacionMesaId() As Integer
            Get
                Return intOperacionMesaId
            End Get
            Set(ByVal Value As Integer)
                intOperacionMesaId = Value
            End Set
        End Property

        Public Property FechaProceso() As String
            Get
                Return strFechaProceso
            End Get
            Set(ByVal Value As String)
                strFechaProceso = Value
            End Set
        End Property

        Public Property TipoOperacionId() As Integer
            Get
                Return intTipoOperacionId
            End Get
            Set(ByVal Value As Integer)
                intTipoOperacionId = Value
            End Set
        End Property

        Public Property TipoOperacion() As String
            Get
                Return strTipoOperacion
            End Get
            Set(ByVal Value As String)
                strTipoOperacion = Value
            End Set
        End Property

        Public Property TipoJuegoId() As Integer
            Get
                Return intTipoJuegoId
            End Get
            Set(ByVal Value As Integer)
                intTipoJuegoId = Value
            End Set
        End Property

        Public Property TipoJuego() As String
            Get
                Return strTipoJuego
            End Get
            Set(ByVal Value As String)
                strTipoJuego = Value
            End Set
        End Property

        Public Property NroMesa() As String
            Get
                Return strNroMesa
            End Get
            Set(ByVal Value As String)
                strNroMesa = Value
            End Set
        End Property

        ''' <summary>
        ''' Dealer|Pitboss|Supervisor|Inspector
        ''' </summary>
        Public Property PersonalAsignado() As String
            Get
                Return strPersonalAsignado
            End Get
            Set(ByVal Value As String)
                strPersonalAsignado = Value
            End Set
        End Property

        Public Property Denominaciones() As String
            Get
                Return strDenominaciones
            End Get
            Set(ByVal Value As String)
                strDenominaciones = Value
            End Set
        End Property

        ''' <summary>
        ''' Concatenar por denominaciones. Ejm. #monedas de 5000|# monedas de 1000|...
        ''' </summary>
        Public Property FlotaFichas() As String
            Get
                Return strFlotaFichas
            End Get
            Set(ByVal Value As String)
                strFlotaFichas = Value
            End Set
        End Property

        Public Property Comentarios() As String
            Get
                Return strComentarios
            End Get
            Set(ByVal Value As String)
                strComentarios = Value
            End Set
        End Property

        Public ReadOnly Property MontoTotal() As Decimal
            Get
                Dim strCantidad() As String = strFlotaFichas.Split("|")
                Dim strDenominacion() As String = strDenominaciones.Split("|")
                Dim intCantidad As Int16 = 0
                decMontoTotal = 0

                For k As Integer = 0 To strDenominacion.Length - 1
                    intCantidad = IIf(strCantidad(k) <> "", strCantidad(k), 0)
                    decMontoTotal += strDenominacion(k) * intCantidad
                Next

                Return decMontoTotal
            End Get
        End Property

        Public Property EstadoId() As Integer
            Get
                Return intEstadoId
            End Get
            Set(ByVal Value As Integer)
                intEstadoId = Value
            End Set
        End Property


    End Class ' clsOperacionMesa

End Namespace ' FJM