'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  rptPuntaje.vb
''  Implementation of the Class rptPuntaje
''  Generated by Enterprise Architect
''  Created on:      05-May-2010 02:58:44 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace FJM
    Public Class rptPuntaje

        Private strFechaProceso As String
        Private intClienteId As Integer
        Private strClienteCodigo As String
        Private strClienteApellidos As String
        Private strClienteNombres As String
        Private intTipoJuegoId As Integer
        Private strTipoJuego As String
        Private decDropTotal As Decimal
        Private decWinLossTotal As Decimal
        Private decApuestaPromTotal As Decimal
        Private decTiempoTotal As Decimal
        Private decPasesHora As Decimal
        Private decHouseEdge As Decimal
        Private decWinTeorico As Decimal

        Public Property FechaProceso() As String
            Get
                Return strFechaProceso
            End Get
            Set(ByVal Value As String)
                strFechaProceso = Value
            End Set
        End Property

        Public Property ClienteId() As Integer
            Get
                Return intClienteId
            End Get
            Set(ByVal Value As Integer)
                intClienteId = Value
            End Set
        End Property

        Public Property ClienteCodigo() As String
            Get
                Return strClienteCodigo
            End Get
            Set(ByVal Value As String)
                strClienteCodigo = Value
            End Set
        End Property

        Public Property ClienteApellidos() As String
            Get
                Return strClienteApellidos
            End Get
            Set(ByVal Value As String)
                strClienteApellidos = Value
            End Set
        End Property

        Public Property ClienteNombres() As String
            Get
                Return strClienteNombres
            End Get
            Set(ByVal Value As String)
                strClienteNombres = Value
            End Set
        End Property

        Public Property TipoJuegoId() As Integer
            Get
                Return intTipoJuegoId
            End Get
            Set(ByVal Value As Integer)
                intTipoJuegoId = Value
            End Set
        End Property

        Public Property TipoJuego() As String
            Get
                Return strTipoJuego
            End Get
            Set(ByVal Value As String)
                strTipoJuego = Value
            End Set
        End Property

        Public Property DropTotal() As Decimal
            Get
                Return decDropTotal
            End Get
            Set(ByVal Value As Decimal)
                decDropTotal = Value
            End Set
        End Property

        Public Property WinLossTotal() As Decimal
            Get
                Return decWinLossTotal
            End Get
            Set(ByVal Value As Decimal)
                decWinLossTotal = Value
            End Set
        End Property

        Public Property ApuestaPromTotal() As Decimal
            Get
                Return decApuestaPromTotal
            End Get
            Set(ByVal Value As Decimal)
                decApuestaPromTotal = Value
            End Set
        End Property

        Public Property TiempoTotal() As Decimal
            Get
                Return decTiempoTotal
            End Get
            Set(ByVal Value As Decimal)
                decTiempoTotal = Value
            End Set
        End Property

        Public Property PasesHora() As Decimal
            Get
                Return decPasesHora
            End Get
            Set(ByVal Value As Decimal)
                decPasesHora = Value
            End Set
        End Property

        Public Property HouseEdge() As Decimal
            Get
                Return decHouseEdge
            End Get
            Set(ByVal Value As Decimal)
                decHouseEdge = Value
            End Set
        End Property

        Public Property WinTeorico() As Decimal
            Get
                Return decWinTeorico
            End Get
            Set(ByVal Value As Decimal)
                decWinTeorico = Value
            End Set
        End Property


    End Class ' rptPuntaje

End Namespace ' CLI