'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  rptRatingDetalle.vb
''  Implementation of the Class rptRatingDetalle
''  Generated by Enterprise Architect
''  Created on:      27-May-2010 05:21:36 p.m.
''  Original author: alejandro.borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace FJM
    Public Class rptRatingDetalle


        Private intClienteId As Integer
        Private strClienteCodigo As String
        Private strClienteNombreCompleto As String
        Private strMovimientoFecha As String
        Private strTipoJuego As String
        Private strMovimientoNroMesa As String
        Private strMovimientoMoneda As String
        Private decMovimientoDrop As Decimal
        Private decMovimientoWinLoss As Decimal
        Private decMovimientoPromedio As Decimal
        Private decMovimientoTiempo As Decimal

        Public Property ClienteId() As Integer
            Get
                Return intClienteId
            End Get
            Set(ByVal Value As Integer)
                intClienteId = Value
            End Set
        End Property

        Public Property ClienteCodigo() As String
            Get
                Return strClienteCodigo
            End Get
            Set(ByVal Value As String)
                strClienteCodigo = Value
            End Set
        End Property

        Public Property ClienteNombreCompleto() As String
            Get
                Return strClienteNombreCompleto
            End Get
            Set(ByVal Value As String)
                strClienteNombreCompleto = Value
            End Set
        End Property

        Public Property TipoJuego() As String
            Get
                Return strTipoJuego
            End Get
            Set(ByVal Value As String)
                strTipoJuego = Value
            End Set
        End Property

        Public Property MovimientoFecha() As String
            Get
                Return strMovimientoFecha
            End Get
            Set(ByVal Value As String)
                strMovimientoFecha = Value
            End Set
        End Property

        Public Property MovimientoNroMesa() As String
            Get
                Return strMovimientoNroMesa
            End Get
            Set(ByVal Value As String)
                strMovimientoNroMesa = Value
            End Set
        End Property

        Public Property MovimientoMoneda() As String
            Get
                Return strMovimientoMoneda
            End Get
            Set(ByVal Value As String)
                strMovimientoMoneda = Value
            End Set
        End Property

        Public Property MovimientoDrop() As Decimal
            Get
                Return decMovimientoDrop
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoDrop = Value
            End Set
        End Property

        Public Property MovimientoWinLoss() As Decimal
            Get
                Return decMovimientoWinLoss
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoWinLoss = Value
            End Set
        End Property

        Public Property MovimientoPromedio() As Decimal
            Get
                Return decMovimientoPromedio
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoPromedio = Value
            End Set
        End Property

        Public Property MovimientoTiempo() As Decimal
            Get
                Return decMovimientoTiempo
            End Get
            Set(ByVal Value As Decimal)
                decMovimientoTiempo = Value
            End Set
        End Property


    End Class ' rptRatingDetalle

End Namespace ' CLI