'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  rptRatingTotal.vb
''  Implementation of the Class rptRatingTotal
''  Generated by Enterprise Architect
''  Created on:      12-May-2010 12:34:43 p.m.
''  Original author: Alejandro Borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace FJM
    Public Class rptRatingTotal


        Private intClienteId As Integer
        Private strClienteCodigo As String
        Private strClienteApellidos As String
        Private strClienteNombres As String
        Private decDropTotal As Decimal
        Private decWinLossTotal As Decimal
        Private decApuestaPromTotal As Decimal
        Private decTiempoTotal As Decimal
        Private strGrupos As String


        Public Property ClienteId() As Integer
            Get
                Return intClienteId
            End Get
            Set(ByVal Value As Integer)
                intClienteId = Value
            End Set
        End Property

        Public Property ClienteCodigo() As String
            Get
                Return strClienteCodigo
            End Get
            Set(ByVal Value As String)
                strClienteCodigo = Value
            End Set
        End Property

        Public Property ClienteApellidos() As String
            Get
                Return strClienteApellidos
            End Get
            Set(ByVal Value As String)
                strClienteApellidos = Value
            End Set
        End Property

        Public Property ClienteNombres() As String
            Get
                Return strClienteNombres
            End Get
            Set(ByVal Value As String)
                strClienteNombres = Value
            End Set
        End Property

        Public Property DropTotal() As Decimal
            Get
                Return decDropTotal
            End Get
            Set(ByVal Value As Decimal)
                decDropTotal = Value
            End Set
        End Property

        Public Property WinLossTotal() As Decimal
            Get
                Return decWinLossTotal
            End Get
            Set(ByVal Value As Decimal)
                decWinLossTotal = Value
            End Set
        End Property

        Public Property ApuestaPromTotal() As Decimal
            Get
                Return decApuestaPromTotal
            End Get
            Set(ByVal Value As Decimal)
                decApuestaPromTotal = Value
            End Set
        End Property

        Public Property TiempoTotal() As Decimal
            Get
                Return decTiempoTotal
            End Get
            Set(ByVal Value As Decimal)
                decTiempoTotal = Value
            End Set
        End Property

        Public Property Grupos() As String
            Get
                Return strGrupos
            End Get
            Set(ByVal Value As String)
                strGrupos = Value
            End Set
        End Property


    End Class ' rptRatingTotal

End Namespace ' CLI