'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.0.0.157/itpe.WebService/wsSeguridad.asmx")>  _
        Public ReadOnly Property bddc_Win_thlaadfs_wsSeguridad() As String
            Get
                Return CType(Me("bddc_Win_thlaadfs_wsSeguridad"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdclienteluxor;Persist Securit"& _ 
            "y Info=True")>  _
        Public ReadOnly Property bdclienteluxorConnectionString() As String
            Get
                Return CType(Me("bdclienteluxorConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdcrmluxor;Persist Security In"& _ 
            "fo=True")>  _
        Public ReadOnly Property bdcrmluxorConnectionString() As String
            Get
                Return CType(Me("bdcrmluxorConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdauxiliarluxor;Persist Securi"& _ 
            "ty Info=True")>  _
        Public ReadOnly Property bdauxiliarluxorConnectionString() As String
            Get
                Return CType(Me("bdauxiliarluxorConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdseguridadluxor;Persist Secur"& _ 
            "ity Info=True")>  _
        Public ReadOnly Property bdseguridadluxorConnectionString() As String
            Get
                Return CType(Me("bdseguridadluxorConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdcliente;Persist Security Inf"& _ 
            "o=True")>  _
        Public ReadOnly Property bdclienteConnectionString() As String
            Get
                Return CType(Me("bdclienteConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdcrm;Persist Security Info=Tr"& _ 
            "ue")>  _
        Public ReadOnly Property bdcrmConnectionString() As String
            Get
                Return CType(Me("bdcrmConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdauxiliar;Persist Security In"& _ 
            "fo=True")>  _
        Public ReadOnly Property bdauxiliarConnectionString() As String
            Get
                Return CType(Me("bdauxiliarConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdseguridad;Persist Security I"& _ 
            "nfo=True")>  _
        Public ReadOnly Property bdseguridadConnectionString() As String
            Get
                Return CType(Me("bdseguridadConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=root;password=root;Persist Security Info=True;database=b"& _ 
            "dcliente")>  _
        Public ReadOnly Property bdclienteConnectionString1() As String
            Get
                Return CType(Me("bdclienteConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=root;password=root;Persist Security Info=True;database=b"& _ 
            "dcrmluxor")>  _
        Public ReadOnly Property bdcrmluxorConnectionString1() As String
            Get
                Return CType(Me("bdcrmluxorConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=root;password=root;Persist Security Info=True;database=b"& _ 
            "dclienteluxor")>  _
        Public ReadOnly Property bdclienteluxorConnectionString1() As String
            Get
                Return CType(Me("bdclienteluxorConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=root;password=root;Persist Security Info=True;database=b"& _ 
            "dauxiliarluxor")>  _
        Public ReadOnly Property bdauxiliarluxorConnectionString1() As String
            Get
                Return CType(Me("bdauxiliarluxorConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdcrmtacna;Persist Security In"& _ 
            "fo=True")>  _
        Public ReadOnly Property bdcrmtacnaConnectionString() As String
            Get
                Return CType(Me("bdcrmtacnaConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("User Id=root;Password=root;Host=10.0.0.59;Database=bdauxiliartacna;Persist Securi"& _ 
            "ty Info=True")>  _
        Public ReadOnly Property bdauxiliartacnaConnectionString() As String
            Get
                Return CType(Me("bdauxiliartacnaConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=FPCTest;password=UserUser2015.FPC;Persist Security Info="& _ 
            "True;database=bdcrm_test")>  _
        Public ReadOnly Property bdcrmTestConnectionString1() As String
            Get
                Return CType(Me("bdcrmTestConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=FPCTest;password=UserUser2015.FPC;Persist Security Info="& _ 
            "True;database=bdauxiliar_test")>  _
        Public ReadOnly Property bdauxiliarTestConnectionString1() As String
            Get
                Return CType(Me("bdauxiliarTestConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=FPCTest;password=UserUser2015.FPC;Persist Security Info="& _ 
            "True;database=bdcliente_test")>  _
        Public ReadOnly Property bdclienteTestConnectionString1() As String
            Get
                Return CType(Me("bdclienteTestConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=10.0.0.59;User Id=FPCTest;password=UserUser2015.FPC;Persist Security Info="& _ 
            "True;database=bdseguridad_test")>  _
        Public ReadOnly Property bdseguridadTestConnectionString1() As String
            Get
                Return CType(Me("bdseguridadTestConnectionString1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=Peru Mysql FPC;uid=root;pwd=root")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.bddc.Win.My.MySettings
            Get
                Return Global.bddc.Win.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
