'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  clsUnidad.vb
''  Implementation of the Class clsUnidad
''  Generated by Enterprise Architect
''  Created on:      06-ene-2011 11:48:13 a.m.
''  Original author: Alejandro Borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Namespace COM
	''' <summary>
	''' Unidad: Locacion de Negocio Thunderbird
	''' </summary>
	Public Class clsUnidad


		''' <summary>
		''' Grupo Parametro: Empresas = 2
		''' </summary>
		Private intEmpresaId As Integer
		Private strEmpresa As String
		Private intUnidadId As Integer
		Private strUnidad As String
		Private strSiglas As String
		''' <summary>
		''' Tabla bdauxiliar.tblaux_ubigeo -> cubg_itemid
		''' </summary>
		Private intUbicacionId As Integer
		''' <summary>
		''' Grupo Parametro: Estado = 1
		''' </summary>
		Private intEstadoId As Integer

		Public Property Empresa() As String
			Get
				Return strEmpresa
			End Get
			Set(ByVal Value as String)
				strEmpresa = Value
			End Set
		End Property

		Public Property EmpresaId() As Integer
			Get
				Return intEmpresaId
			End Get
			Set(ByVal Value as Integer)
				intEmpresaId = Value
			End Set
		End Property

		Public Property UnidadId() As Integer
			Get
				Return intUnidadId
			End Get
			Set(ByVal Value as Integer)
				intUnidadId = Value
			End Set
		End Property

		Public Property Unidad() As String
			Get
				Return strUnidad
			End Get
			Set(ByVal Value as String)
				strUnidad = Value
			End Set
		End Property

		Public Property Siglas() As String
			Get
				Return strSiglas
			End Get
			Set(ByVal Value as String)
				strSiglas = Value
			End Set
		End Property

		''' <summary>
		''' Tabla bdauxiliar.tblaux_ubigeo -> cubg_itemid
        ''' </summary>
        ''' 

		Public Property UbicacionId() As Integer
			Get
				Return intUbicacionId
			End Get
			Set(ByVal Value as Integer)
				intUbicacionId = Value
			End Set
		End Property

		Public Property EstadoId() As Integer
			Get
				Return intEstadoId
			End Get
			Set(ByVal Value as Integer)
				intEstadoId = Value
			End Set
		End Property


	End Class ' clsUnidad

End Namespace ' COM