'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''
''  clsOperacionCaja.vb
''  Implementation of the Class clsOperacionCaja
''  Generated by Enterprise Architect
''  Created on:      14-dic-2010 12:24:00 p.m.
''  Original author: Alejandro Borjas
''  
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''  Modification history:
''  
''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''



Option Explicit On
Option Strict On

Imports bddc.BEC.COM

Namespace FCB
    Public Class clsOperacionCaja
        Inherits COM.clsAuditoria


        Private intOperacionCajaId As Integer
        Private strOperacionCodigo As String
        Private strOperacionFecha As String
        Private strOperacionHora As String
        Private strSujetoObligado As String
        Private strOficialCumplimiento As String
        Private intOperacionMontoMonedaId As Integer
        Private decOperacionMontoImporte As Decimal
        Private intOperacionModalidadId As Integer
        Private strOperacionMonto As String
        Private decOperacionTipoCambio As Decimal
        Private strOperacionReferencia As String
        Private strOperacionTarjetaNum As String
        Private strOperacionCaja As String
        Private intOperacionTipoId As Integer
        Private intClienteId As Integer
        Private strClienteDocumento As String
        Private strClienteNombreCompleto As String
        Private intEstadoId As Integer
        Private intOperacionFichaCantidad As Integer
        Private decOperacionFichaDenominacion As Decimal
        Private strOperacionMaquinaNum As String
        Private strOperacionComentario As String
        Private intUserId As Integer
        Private strUserName As String
        Private strNumRegistro As String
        Private TipoTarjeta As String
        Private Caja As String
        Private TipoDoc As Integer
        Private NumDoc As String



        Public Sub New()

            strOperacionCodigo = ""
            strOperacionFecha = ""
            strSujetoObligado = ""
            strOficialCumplimiento = ""
            strOperacionMonto = ""
            strOperacionTarjetaNum = ""
            strOperacionCaja = ""
            strClienteNombreCompleto = ""
            strOperacionMaquinaNum = ""
        End Sub

        Public Property OperacionCajaId() As Integer
            Get
                Return intOperacionCajaId
            End Get
            Set(ByVal Value As Integer)
                intOperacionCajaId = Value
            End Set
        End Property

        Public Property OperacionCodigo() As String
            Get
                Return strOperacionCodigo
            End Get
            Set(ByVal Value As String)
                strOperacionCodigo = Value
            End Set
        End Property

        Public Property OperacionFecha() As String
            Get
                Return strOperacionFecha
            End Get
            Set(ByVal Value As String)
                strOperacionFecha = Value
            End Set
        End Property

        Public Property SujetoObligado() As String
            Get
                Return strSujetoObligado
            End Get
            Set(ByVal Value As String)
                strSujetoObligado = Value
            End Set
        End Property

        Public Property OficialCumplimiento() As String
            Get
                Return strOficialCumplimiento
            End Get
            Set(ByVal Value As String)
                strOficialCumplimiento = Value
            End Set
        End Property

        Public Property OperacionMontoMonedaId() As Integer
            Get
                Return intOperacionMontoMonedaId
            End Get
            Set(ByVal Value As Integer)
                intOperacionMontoMonedaId = Value
            End Set
        End Property

        Public Property OperacionMontoImporte() As Decimal
            Get
                Return decOperacionMontoImporte
            End Get
            Set(ByVal Value As Decimal)
                decOperacionMontoImporte = Value
            End Set
        End Property

        Public Property OperacionTipoCambio() As Decimal
            Get
                Return decOperacionTipoCambio
            End Get
            Set(ByVal Value As Decimal)
                decOperacionTipoCambio = Value
            End Set
        End Property

        Public Property OperacionModalidadId() As Integer
            Get
                Return intOperacionModalidadId
            End Get
            Set(ByVal Value As Integer)
                intOperacionModalidadId = Value
            End Set
        End Property

        Public Property OperacionTipoId() As Integer
            Get
                Return intOperacionTipoId
            End Get
            Set(ByVal Value As Integer)
                intOperacionTipoId = Value
            End Set
        End Property

        Public Property OperacionReferencia() As String
            Get
                Return strOperacionReferencia
            End Get
            Set(ByVal Value As String)
                strOperacionReferencia = Value
            End Set
        End Property

        Public Property OperacionTarjetaNum() As String
            Get
                Return strOperacionTarjetaNum
            End Get
            Set(ByVal Value As String)
                strOperacionTarjetaNum = Value
            End Set
        End Property

        Public Property OperacionCaja() As String
            Get
                Return strOperacionCaja
            End Get
            Set(ByVal Value As String)
                strOperacionCaja = Value
            End Set
        End Property

        Public Property ClienteId() As Integer
            Get
                Return intClienteId
            End Get
            Set(ByVal Value As Integer)
                intClienteId = Value
            End Set
        End Property

        Public Property ClienteNombreCompleto() As String
            Get
                Return strClienteNombreCompleto
            End Get
            Set(ByVal Value As String)
                strClienteNombreCompleto = Value
            End Set
        End Property

        Public Property ClienteDocumento() As String
            Get
                Return strClienteDocumento
            End Get
            Set(ByVal Value As String)
                strClienteDocumento = Value
            End Set
        End Property

        Public Property OperacionHora() As String
            Get
                Return strOperacionHora
            End Get
            Set(ByVal Value As String)
                strOperacionHora = Value
            End Set
        End Property

        Public Property OperacionMonto() As String
            Get
                Return strOperacionMonto
            End Get
            Set(ByVal Value As String)
                strOperacionMonto = Value
            End Set
        End Property

        Public Property OperacionFichaCantidad() As Integer
            Get
                Return intOperacionFichaCantidad
            End Get
            Set(ByVal Value As Integer)
                intOperacionFichaCantidad = Value
            End Set
        End Property

        Public Property OperacionFichaDenominacion() As Decimal
            Get
                Return decOperacionFichaDenominacion
            End Get
            Set(ByVal Value As Decimal)
                decOperacionFichaDenominacion = Value
            End Set
        End Property

        Public Property OperacionMaquinaNum() As String
            Get
                Return strOperacionMaquinaNum
            End Get
            Set(ByVal Value As String)
                strOperacionMaquinaNum = Value
            End Set
        End Property

        Public Property OperacionComentario() As String
            Get
                Return strOperacionComentario
            End Get
            Set(ByVal Value As String)
                strOperacionComentario = Value
            End Set
        End Property

        Public Property EstadoId() As Integer
            Get
                Return intEstadoId
            End Get
            Set(ByVal Value As Integer)
                intEstadoId = Value
            End Set
        End Property

        Public Property NumRegistro() As String
            Get
                Return strNumRegistro
            End Get
            Set(ByVal Value As String)
                strNumRegistro = Value
            End Set
        End Property

        Public Property UserId() As Integer
            Get
                Return intUserId
            End Get
            Set(ByVal Value As Integer)
                intUserId = Value
            End Set
        End Property

        Public Property UserName() As String
            Get
                Return strUserName
            End Get
            Set(ByVal Value As String)
                strUserName = Value
            End Set
        End Property

        Public Property TipoTarjetaCred() As String
            Get
                Return TipoTarjeta
            End Get
            Set(ByVal Value As String)
                TipoTarjeta = Value
            End Set
        End Property

        Public Property NombreCaja() As String
            Get
                Return Caja
            End Get
            Set(ByVal Value As String)
                Caja = Value
            End Set
        End Property

        Public Property TipoDocumento() As Integer
            Get
                Return TipoDoc
            End Get
            Set(ByVal Value As Integer)
                TipoDoc = Value
            End Set
        End Property

        Public Property NumeroDocumento() As String
            Get
                Return NumDoc
            End Get
            Set(ByVal Value As String)
                NumDoc = Value
            End Set
        End Property

    End Class ' clsOperacionCaja

End Namespace ' FCB